local QBCore = exports['et-core']:GetCoreObject()

if Config.UseBlips then
    CreateThread(function()
        -- LDBlip = AddBlipForCoord(LumberDepo.coords)
        -- SetBlipSprite (LDBlip, LumberDepo.SetBlipSprite)
        -- SetBlipDisplay(LDBlip, LumberDepo.SetBlipDisplay)
        -- SetBlipScale  (LDBlip, LumberDepo.SetBlipScale)
        -- SetBlipAsShortRange(LDBlip, true)
        -- SetBlipColour(LDBlip, LumberDepo.SetBlipColour)
        -- BeginTextCommandSetBlipName("STRING")
        -- AddTextComponentSubstringPlayerName(LumberDepo.BlipLabel)
        -- EndTextCommandSetBlipName(LDBlip)
        
        LJPBlip = AddBlipForCoord(LumberProcessor.coords)
        SetBlipSprite (LJPBlip, LumberProcessor.SetBlipSprite)
        SetBlipDisplay(LJPBlip, LumberProcessor.SetBlipDisplay)
        SetBlipScale  (LJPBlip, LumberProcessor.SetBlipScale)
        SetBlipAsShortRange(LJPBlip, true)
        SetBlipColour(LJPBlip, LumberProcessor.SetBlipColour)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName(LumberProcessor.BlipLabel)
        EndTextCommandSetBlipName(LJPBlip)

        -- LJSBlip = AddBlipForCoord(LumberSeller.coords)
        -- SetBlipSprite (LJSBlip, LumberSeller.SetBlipSprite)
        -- SetBlipDisplay(LJSBlip, LumberSeller.SetBlipDisplay)
        -- SetBlipScale  (LJSBlip, LumberSeller.SetBlipScale)
        -- SetBlipAsShortRange(LJSBlip, true)
        -- SetBlipColour(LJSBlip, LumberSeller.SetBlipColour)
        -- BeginTextCommandSetBlipName("STRING")
        -- AddTextComponentSubstringPlayerName(LumberSeller.BlipLabel)
        -- EndTextCommandSetBlipName(LJSBlip)

        LJTR = AddBlipForCoord(vector3(-506.05, 5384.73, 74.88))
        SetBlipSprite (LJTR, 79)
        SetBlipDisplay(LJTR, 6)
        SetBlipScale  (LJTR, 1.0)
        SetBlipAsShortRange(LJTR, true)
        SetBlipColour(LJTR, 2)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName("~b~[Nghề Nghiệp] Chặt gỗ")
        EndTextCommandSetBlipName(LJTR)

    end)
end