var tableauQuestion = [
    {   question : "Bạn đang lái xe phía trước có 1 xe cứu thương đang phát tín hiệu ưu tiên bạn có được phép vượt hay không?",
        propositionA : "Được vượt khi đang trên cầu",
        propositionB : "Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông",
        propositionC : "Không được vượt",
        propositionD : "Được vượt khi đảm bảo an toàn",
        reponse : "C"},

    {   question : "Người điều khiển mô tô phải giảm tốc độ và hết sức thận trọng khi qua những đoạn đường nào dưới đây?",
        propositionA : "Đường ướt, đường có sỏi cát trên nền đường",
        propositionB : "Đường hẹp có nhiều điểm giao cắt từ 2 phía",
        propositionC : "Tất cả các ý trên",
        propositionD : "Đường đèo dốc, vòng liên tục",
        reponse : "C"},

    {   question : "Khi điều khiền phương tiện thao gia giao thông, những hành vi nào dưới đây bị nghiêm cấm?",
        propositionA : "Lạng lách, đánh võng trên đường bộ",
        propositionB : "Thay đổi tay số của xe trên đường bộ",
        propositionC : "Thay đổi tốc độ của xe trên đường bộ",
        propositionD : "Tất cả các ý trên",
        reponse : "A"},

  {   question : "Việc lái xe mô tô, ô tô, máy kéo ngay sau khi uống rượu, bia có được phép hay không?",
        propositionA : "Có được phép",
        propositionB : "Chỉ được lái ở tốc độ chậm và quãng đường ngắn",
        propositionC : "Chỉ được lái nếu trong cơ thể có nồng độ thấp",
        propositionD : "Không được phép",
        reponse : "D"},

  {   question : "Điều khiển xe ô tô trong trời mưa, người lái xe phải xử lí như thế nào để an toàn?",
        propositionA : "Giảm tốc độ.",
        propositionB : "Không nên phanh gấp.",
        propositionC : "Tất cả ý trên.",
        propositionD : "Mở chế dộ gạt nước.",
        reponse : "C"},

  {   question : "Khi lùi xe người lái xe phải làm gì để bảo đảm an toàn?",
        propositionA : "Quan sát phía trước và cho lùi xe ở tốc độ chậm được không.",
        propositionB : "Lợi dụng nơi đường giao nhau để lùi.",
        propositionC : "Lùi xe ở ngã tư.",
        propositionD : "Quan sát phía sau có tín hiệu cần thiết và khi thấy an toàn mới được lùi.",
        reponse : "D"},

  {   question : "Phóng nhanh, vượt ẩu, vượt đèn đỏ được coi là hành vi như thế nào?",
        propositionA : "Có gì đâu, bình thường.",
        propositionB : "Là dân chơi.",
        propositionC : "Là người có văn hóa giao thông.",
        propositionD : "Là người thiếu văn hóa.",
        reponse : "D"},

  {   question : "Người bao nhiêu tuổi trở kên mới được điều khiển xe ô tô?",
        propositionA : "16 tuổi",
        propositionB : "17 tuổi",
        propositionC : "18 tuổi",
        propositionD : "19 tuổi",
        reponse : "C"},

  {   question : "Đua xe chỉ được thực hiện khi nào?",
        propositionA : "Diễn ra trên đường phố không có người qua lại.",
        propositionB : "Được người dân ủng hộ.",
        propositionC : "Thích là đua.",
        propositionD : "Được cơ quan cấp phép.",
        reponse : "D"},

  {   question : "Chạy xe quá tốc độ quy định có bị cấm hay không?",
        propositionA : "Chạy thoải mái.",
        propositionB : "Không.",
        propositionC : "Xe mẹ mua không đua mẹ đánh.",
        propositionD : "Có.",
        reponse : "D"},
]
